"""update table users add is_muted column

Revision ID: 1cb1be2f1d0a
Revises: 77278dfb78bb
Create Date: 2026-02-12 00:57:36.690620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cb1be2f1d0a'
down_revision = '77278dfb78bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_muted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_muted')

    # ### end Alembic commands ###
