"""added Logs table

Revision ID: 38924e6f3b91
Revises: cf6db090f453
Create Date: 2026-02-13 00:23:18.105161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38924e6f3b91'
down_revision = 'cf6db090f453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    # ### end Alembic commands ###
