"""add time muted

Revision ID: 57f01740b1c6
Revises: fcdf2fe10e9e
Create Date: 2026-02-12 01:02:02.885253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57f01740b1c6'
down_revision = 'fcdf2fe10e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_muted', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('time_muted')

    # ### end Alembic commands ###
