"""update table users add is_banned column

Revision ID: 77278dfb78bb
Revises: d7a61f738022
Create Date: 2026-02-12 00:49:29.724106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77278dfb78bb'
down_revision = 'd7a61f738022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_banned',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_banned',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
