"""empty message

Revision ID: 8625a9cfa849
Revises: cf1c4c1da0ae
Create Date: 2026-02-13 17:04:08.583214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8625a9cfa849'
down_revision = 'cf1c4c1da0ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)

    # ### end Alembic commands ###
