"""mute_date

Revision ID: cf6db090f453
Revises: 57f01740b1c6
Create Date: 2026-02-12 19:49:52.115547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6db090f453'
down_revision = '57f01740b1c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mute_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('time_muted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_muted', sa.DATETIME(), nullable=True))
        batch_op.drop_column('mute_date')

    # ### end Alembic commands ###
