"""update table users update is_muted column

Revision ID: fcdf2fe10e9e
Revises: 1cb1be2f1d0a
Create Date: 2026-02-12 00:59:08.643880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcdf2fe10e9e'
down_revision = '1cb1be2f1d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_muted',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_muted',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
